In [1]:
import sys
import os
import pathlib


ROOT_DIR = str(pathlib.Path(os.getcwd()).parent.parent)
sys.path.append(ROOT_DIR)

import numpy as np
import cv2
from diffusion_policy.env.wam_pick.utils import WAM_fwd_kinematics

In [20]:
qpos = np.load("/Users/dylanmiller/Projects/DiffusionPolicy/diffusion_policy/data/pick/all_final_qpos.npy")
pick_loc = np.load("/Users/dylanmiller/Projects/DiffusionPolicy/diffusion_policy/data/pick/all_init_pick_loc.npy")

In [22]:
np.argmin(pick_loc, axis=0)

array([23, 27])

In [27]:
ends = []
for i in range(qpos.shape[0]):
    ends.append(WAM_fwd_kinematics(qpos[i], 7))

ends_arr = np.array(ends)

In [29]:
ends_arr.min(axis=0)

array([ 0.40543954, -0.27052517,  0.0710732 ])

In [30]:
ends_arr.max(axis=0)

array([0.8175339 , 0.28296449, 0.13107691])

In [32]:
pick_loc.max(axis=0)

array([439.4395146 , 488.46530148])

# Find Homography

In [15]:
pts_src = np.array([[241, 142], [235, 495], [479, 526], [480, 118]])
pts_dst = np.array([[0, 0],[0, 1],[1, 1],[1, 0]])

h, status = cv2.findHomography(pts_src, pts_dst)

In [17]:
a = h @ np.array([[600, 479, 1]]).T
a / a[-1]

array([[1.40226703],
       [0.85980953],
       [1.        ]])

In [32]:
pick_loc_hom = np.concatenate([pick_loc, np.ones((pick_loc.shape[0], 1))], axis=1)

In [30]:
np.ones((pick_loc.shape[0], 1)).shape

(30, 1)

In [38]:
a = (h @ pick_loc_hom.T)
res = a / a[-1, :]

In [45]:
res[:, 23]

array([-0.10631764,  0.47640022,  1.        ])

In [49]:
res.max(axis=1)

array([0.85618893, 0.92036586, 1.        ])

In [48]:
h

array([[ 5.80416032e-03,  9.86542830e-05, -1.41281154e+00],
       [ 3.49402610e-04,  3.47946765e-03, -5.78290436e-01],
       [ 7.80496521e-04,  8.63413816e-05,  1.00000000e+00]])